### ISSUE TITLE
Error: channel closed 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-languageserver-node#36]
```
Error: channel closed 
at ChildProcess.target.send (internal/child_process.js:509:16) 
at IPCMessageWriter.write (/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageWriter.js:34:22) 
at Object.connection.sendNotification (/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:180:27) 
at Object.result.didChangeTextDocument (/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:55:70) 
at Delayer.<anonymous> (/dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/main.js:373:28) 
at /dbaeumer.vscode-eslint-0.10.13/node_modules/vscode-languageclient/lib/utils/async.js:27:36 
```

**Comment by dbaeumer** [comment]
Dups #34
