### ISSUE TITLE
Exception when return undefined as hover content

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-languageserver-node#46]
On the language server side I return undefined as hover content.

That results the following exception on the client side:
shell.ts:408 Illegal argument: Error: Illegal argument
    at new e (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:16893)
    at asHover (/home/aeschli/workspaces/vscode/extensions/css/node_modules/vscode-languageclient/lib/protocolConverter.js:70:12)

Clearly a user error, but should be handled on the server side, or handled gracefully

**Comment by dbaeumer** [comment]
As discussed with @aeschli this requires literal checking code for all literal defined in protocol.ts. @aeschli is working on a separate types npm module. As soon as we have that we can add the code there.
