### ISSUE TITLE
VSCode online, resolveModulePath fail

### ISSUE THREAD

**Issue by lifeart** [microsoft/vscode-languageserver-node#545]
given: an not installed dependency, for example `ember-template-lint`.

`let nodePath = resolveGlobalNodePath();`
calling `resolveModulePath(project.root, 'ember-template-lint', nodePath)` cause langerver fail, and try/catch can't handle this situation.

```

Error: spawn /home/vsonline/.vscode-remote/bin/8795a9889db74563ddd43eb0a897a2384129a619/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ' +
    '/home/vsonline/.vscode-remote/bin/8795a9889db74563ddd43eb0a897a2384129a619/node',
  path: '/home/vsonline/.vscode-remote/bin/8795a9889db74563ddd43eb0a897a2384129a619/node',
  spawnargs: [
    '-e',
    'var p = ' +
      "process;p.on('message',function(m){if(m.c==='e'){p.exit(0);}else " +
      "if(m.c==='rs'){try{var " +
      "r=require.resolve(m.a);p.send({c:'r',s:true,r:r});}catch(err){p.send({c:'r',s:false});}}});",
    ''
  ]
}
[Info  - 8:54:20 PM] Connection to server got closed. Server will restart.
```

refs: https://github.com/microsoft/vscode-languageserver-node/blob/0ddb66e06883080c23ee885e55076a1130e8db6d/server/src/files.ts#L52

**Comment by lifeart** [comment]
`resolveGlobalNodePath` return non existing path

**Comment by lifeart** [comment]
fix for langserver: https://github.com/lifeart/ember-language-server/commit/cec2e30b9deaf4f84d213c94e9c32287a75a7241
