### ISSUE TITLE
Startup takes 3mins, NO_UPDATE_NOTIFIER

### ISSUE THREAD

**Issue by AriPerkkio** [microsoft/vscode-languageserver-node#551]
First of all, thanks for the great extension!

Starting the extensions takes 3 minutes when running it on environment behind proxy. This issue is was recently seen on prettier extension as well, and was fixed for 3.17.0. https://github.com/prettier/prettier-vscode/issues/1143

```
[Info  - 8.31.40] ESLint server stopped.
[Info  - 8.31.41] ESLint server running in node v12.4.0
[Info  - 8.31.41] ESLint server is running.
Uncaught exception received.
Error: spawn C:\Users\xx\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[Info  - 8.34.52] ESLint library loaded from: C:\Users\xx\<path-to-projecta-root>\node_modules\eslint\lib\api.js
```
Time between the last two timestamps is ~3min.

This eslint plugin is using the same methods to run npm on child_process:
https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L511
https://github.com/microsoft/vscode-languageserver-node/blob/master/server/src/files.ts#L140
```js
let stdout = spawnSync(npmCommand, ['config', 'get', 'prefix'], options).stdout;
```

The issue can be fixed by setting environment variable NO_UPDATE_NOTIFIER to true.
https://github.com/prettier/prettier-vscode/issues/1143#issuecomment-567369919

I'd like to see this fixed on the extension itself rather than set up these env variables on all our developer machines.

**Comment by AriPerkkio** [comment]
Yes, that should do it. The fix looks OK.
Thanks for taking action quickly!
