### ISSUE TITLE
Is 3.15 out?

### ISSUE THREAD

**Issue by Razzeee** [microsoft/vscode-languageserver-node#560]
https://microsoft.github.io/language-server-protocol/specifications/specification-current/ referees to 3.15 as current. So has it been released? Should it work with the vscode version from December?

I tried to get it to work yesterday, but it kept crashing on me. https://github.com/elm-tooling/elm-language-client-vscode/tree/new-language-server-version

**Comment by Razzeee** [comment]
I'm basically getting `Error: Unhandled method window/workDoneProgress/create` so I'm not sure if I'm missing anything on my end.

Here's the complete log:

```
Debugger listening on ws://127.0.0.1:6010/7e3754b2-0ec9-4168-a2d5-89c563939045
For help, see: https://nodejs.org/en/docs/inspector
[Info  - 10:45:42 AM] Loading Elm tree-sitter syntax from ../elm-language-client-vscode/server/out/tree-sitter-elm.wasm
[Info  - 10:45:42 AM] Found 1 elm.json files for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:42 AM] Found 1 unique elmWorkspaces for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:42 AM] Starting language server for folder: file:///home/razze/Development/elm-multi-source-dirs
Error: Unhandled method window/workDoneProgress/create
Error: Unhandled method window/workDoneProgress/create

/home/razze/Development/elm-language-client-vscode/server/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),Mod
abort(Error: Unhandled method window/workDoneProgress/create). Build with -s ASSERTIONS=1 for more info.
[Info  - 10:45:42 AM] Connection to server got closed. Server will restart.
Debugger listening on ws://127.0.0.1:6010/38a94529-ddbf-4aaf-8eb3-68e98e96a324
For help, see: https://nodejs.org/en/docs/inspector
[Info  - 10:45:43 AM] Loading Elm tree-sitter syntax from ../elm-language-client-vscode/server/out/tree-sitter-elm.wasm
[Info  - 10:45:43 AM] Found 1 elm.json files for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:43 AM] Found 1 unique elmWorkspaces for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:43 AM] Starting language server for folder: file:///home/razze/Development/elm-multi-source-dirs
Error: Unhandled method window/workDoneProgress/create
Error: Unhandled method window/workDoneProgress/create

/home/razze/Development/elm-language-client-vscode/server/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),Mod
abort(Error: Unhandled method window/workDoneProgress/create). Build with -s ASSERTIONS=1 for more info.
[Info  - 10:45:43 AM] Connection to server got closed. Server will restart.
[Error - 10:45:43 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 10:45:43 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)
Debugger listening on ws://127.0.0.1:6010/e4fc4994-a873-4550-9d7b-c7d08bf6ee89
For help, see: https://nodejs.org/en/docs/inspector
[Info  - 10:45:43 AM] Loading Elm tree-sitter syntax from ../elm-language-client-vscode/server/out/tree-sitter-elm.wasm
[Info  - 10:45:43 AM] Found 1 elm.json files for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:43 AM] Found 1 unique elmWorkspaces for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:43 AM] Starting language server for folder: file:///home/razze/Development/elm-multi-source-dirs
Error: Unhandled method window/workDoneProgress/create
Error: Unhandled method window/workDoneProgress/create

/home/razze/Development/elm-language-client-vscode/server/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),Mod
abort(Error: Unhandled method window/workDoneProgress/create). Build with -s ASSERTIONS=1 for more info.
[Info  - 10:45:43 AM] Connection to server got closed. Server will restart.
[Error - 10:45:43 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.onexit (internal/child_process.js:283:5)
[Error - 10:45:43 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.onexit (internal/child_process.js:283:5)
Debugger listening on ws://127.0.0.1:6010/1ea6870f-ec38-4a73-bb44-372bbd84bbee
For help, see: https://nodejs.org/en/docs/inspector
[Info  - 10:45:44 AM] Loading Elm tree-sitter syntax from ../elm-language-client-vscode/server/out/tree-sitter-elm.wasm
[Info  - 10:45:44 AM] Found 1 elm.json files for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:44 AM] Found 1 unique elmWorkspaces for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:44 AM] Starting language server for folder: file:///home/razze/Development/elm-multi-source-dirs
Error: Unhandled method window/workDoneProgress/create
Error: Unhandled method window/workDoneProgress/create

/home/razze/Development/elm-language-client-vscode/server/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),Mod
abort(Error: Unhandled method window/workDoneProgress/create). Build with -s ASSERTIONS=1 for more info.
[Info  - 10:45:44 AM] Connection to server got closed. Server will restart.
[Error - 10:45:44 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.onexit (internal/child_process.js:283:5)
[Error - 10:45:44 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.onexit (internal/child_process.js:283:5)
Debugger listening on ws://127.0.0.1:6010/2c084d74-0408-4905-a5af-f5fc10da41f8
For help, see: https://nodejs.org/en/docs/inspector
[Info  - 10:45:44 AM] Loading Elm tree-sitter syntax from ../elm-language-client-vscode/server/out/tree-sitter-elm.wasm
[Info  - 10:45:44 AM] Found 1 elm.json files for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:44 AM] Found 1 unique elmWorkspaces for workspace /home/razze/Development/elm-multi-source-dirs
[Info  - 10:45:44 AM] Starting language server for folder: file:///home/razze/Development/elm-multi-source-dirs
Error: Unhandled method window/workDoneProgress/create
Error: Unhandled method window/workDoneProgress/create

/home/razze/Development/elm-language-client-vscode/server/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r,o=!1,u=!1,s=!1;o="object"==typeof window,u="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,s=n&&!o&&!u,r=!o&&!s&&!u;var a,i,l,_,d="";s?(d=__dirname+"/",a=function(e,t){var n;return l||(l=require("fs")),_||(_=require("path")),e=_.normalize(e),n=l.readFileSync(e),t?n:n.toString()},i=function(e){var t=a(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(Module.thisProgram=process.argv[1].replace(/\\/g,"/")),Mod
abort(Error: Unhandled method window/workDoneProgress/create). Build with -s ASSERTIONS=1 for more info.
[Error - 10:45:44 AM] Connection to server got closed. Server will not be restarted.
[Error - 10:45:44 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)
[Error - 10:45:44 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/razze/Development/elm-language-client-vscode/client/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:200:13)
	at Pipe.<anonymous> (net.js:586:12)

```

**Comment by dbaeumer** [comment]
That is very strange. On the client side do you hit the breakpoint here: https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/progress.ts#L28 which should install the progress feature.

And are you trying to call progress from within the initialize method on the server? Sending requests to the client is not supported during that phase. To still allow to report progress in initialize you need to do the following:

- Set progressOnInitialization (see https://github.com/microsoft/vscode-languageserver-node/blob/master/testbed/client/src/extension.ts#L34) 
- Use the progress token that comes with the params in the initialize request. The LSP node server library unwraps this automatically (https://github.com/microsoft/vscode-languageserver-node/blob/master/testbed/server/src/server.ts#L101) but you might need to use the `workDoneToken` property on the params.

**Comment by Razzeee** [comment]
Yeah, I'm trying to do it before initialize, to report how far we're with indexing :)

**Comment by Razzeee** [comment]
Doesn't crash anymore after those changes, but I don't think I'm seeing progress? I should be getting a toast right?

**Comment by dbaeumer** [comment]
Yes, you should. Did you send a begin notification on the token (https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.progress.ts#L25).

**Comment by Razzeee** [comment]
Yes, I tried both with zero progress and without. I guess my initialize is to fast?

**Comment by dbaeumer** [comment]
That could be. There is some delay before we show the progress to avoid flickering.

**Comment by dbaeumer** [comment]
OK to close.
