### ISSUE TITLE
Latest client / server package is out of sync with the last protocol

### ISSUE THREAD

**Issue by david-driscoll** [microsoft/vscode-languageserver-node#651]
I was updating to the most recent `next` tag for the client/server/protocol and now the semantic tokens proposal is causing the following error to happen.

```
[Error - 8:26:37 PM] Starting client failed
TypeError: Cannot read property 'Relative' of undefined
	at SemanticTokensFeature.fillClientCapabilities (d:\Development\Omnisharp\csharp-language-server-protocol\vscode-testextension\node_modules\vscode-languageclient\lib\common\semanticTokens.proposed.js:86:78)
	at LanguageClient.computeClientCapabilities (d:\Development\Omnisharp\csharp-language-server-protocol\vscode-testextension\node_modules\vscode-languageclient\lib\common\client.js:2452:21)
	at LanguageClient.initialize (d:\Development\Omnisharp\csharp-language-server-protocol\vscode-testextension\node_modules\vscode-languageclient\lib\common\client.js:2082:32)
	at d:\Development\Omnisharp\csharp-language-server-protocol\vscode-testextension\node_modules\vscode-languageclient\lib\common\client.js:2049:25
```

The code at that point is:
```
capability.formats = [protocol_semanticTokens_proposed_1.TokenFormat.Relative];
```

However `TokenFormat` is not defined in the related protocol file when I looked on disk.  This appears to be because the last time the protocol package was pushed was a little over a month ago.

Thanks!

cc @TylerLeonhardt

**Comment by dbaeumer** [comment]
@david-driscoll sorry for that. Definitely my mistake :-)

**Comment by dbaeumer** [comment]
Release new NPM packages.

**Comment by david-driscoll** [comment]
Thanks @dbaeumer !
