### ISSUE TITLE
error on client.registerProposedFeatures

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-languageserver-node#811]
Repro step:
- add `languageClient.registerProposedFeatures();` in extention code.

Is it related to `proposed.diagnostic`?

```
workbench.desktop.main.js:sourcemap:768 TypeError: vscode_1.window.openEditors is not iterable
    at openEditorsHandler (c:\Users\admin\git\microsoft\vscode-extension-samples\lsp-sample\client\node_modules\vscode-languageclient\lib\common\proposed.diagnostic.js:37:48)
    at new EditorTracker (c:\Users\admin\git\microsoft\vscode-extension-samples\lsp-sample\client\node_modules\vscode-languageclient\lib\common\proposed.diagnostic.js:41:9)
    at new DiagnosticFeature (c:\Users\admin\git\microsoft\vscode-extension-samples\lsp-sample\client\node_modules\vscode-languageclient\lib\common\proposed.diagnostic.js:530:30)
    at Object.createAll (c:\Users\admin\git\microsoft\vscode-extension-samples\lsp-sample\client\node_modules\vscode-languageclient\lib\common\commonClient.js:59:13)
    at LanguageClient.registerProposedFeatures (c:\Users\admin\git\microsoft\vscode-extension-samples\lsp-sample\client\node_modules\vscode-languageclient\lib\common\commonClient.js:27:48)
    at activate (c:\Users\admin\git\microsoft\vscode-extension-samples\lsp-sample\client\src\extension.ts:57:9)
    at Function._callActivateOptional (c:\Users\admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:14900)
    at Function._callActivate (c:\Users\admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:14576)
    at c:\Users\admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:12779
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```

**Comment by dbaeumer** [comment]
Yes, it is and I am aware of it. The next version still works with stable 1.60.0 but not with latest insider (some proposed API changes)

**Comment by dbaeumer** [comment]
Fixed it yesterday to probe for the old and new API.
