### ISSUE TITLE
Stream read errors result in uncaught exceptions

### ISSUE THREAD

**Issue by mroch** [microsoft/vscode-languageserver-node#870]
`ReadableStreamMessageReader` throws exceptions if `Content-Length` is invalid, which end up as uncaught exceptions instead of going through `onError`. See the tests in #871 for an example. Without the try/catch, the test fails:

```
  1) Messages
       Read without Content-Length:
     Uncaught Error: Header must provide a Content-Length property.
      at StreamMessageReader.onData (lib/common/messageReader.js:137:27)
      at Readable.<anonymous> (lib/common/messageReader.js:121:18)
      at Readable.read (_stream_readable.js:512:10)
      at flow (_stream_readable.js:985:34)
      at resume_ (_stream_readable.js:966:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

  2) Messages
       Read with invalid Content-Length:
     Uncaught Error: Content-Length value must be a number.
      at StreamMessageReader.onData (lib/common/messageReader.js:141:27)
      at Readable.<anonymous> (lib/common/messageReader.js:121:18)
      at Readable.read (_stream_readable.js:512:10)
      at flow (_stream_readable.js:985:34)
      at resume_ (_stream_readable.js:966:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

This was previously reported in #270, but it has not been fixed.

**Comment by dbaeumer** [comment]
This got changed. The code now calls `this.fireError`. See https://github.com/microsoft/vscode-languageserver-node/blob/f02ec883a68c6ee0e07a512c2114847f5f8c9d29/jsonrpc/src/common/messageReader.ts#L249

**Comment by dbaeumer** [comment]
See also https://github.com/microsoft/vscode-languageserver-node/pull/1151
