### ISSUE TITLE
VS Code tries to read 'range' field from TextEdit which is null

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-languageserver-node#95]
_From @mniewrzal on September 12, 2016 10:57_
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:34:58.760Z)
- OS Version: Linux x64 4.7.2-201.fc24.x86_64

Steps to Reproduce:

After sending CompletionItem[] as a response for 'textDocument/completion' nothing is happening, no proposals. Developer tools console shows error.

Response for method: 'textDocument/completion':

```
Content-Type: application/vscode-jsonrpc; charset=utf8
Content-Length: 187

{"jsonrpc":"2.0","id":1,"result":[{"label":"abstract","kind":14,"detail":null,"documentation":null,"sortText":null,"filterText":null,"insertText":"abstract","textEdit":null,"data":null}]}
```

Developer tools console shows:

```
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:121 Cannot read property 'range' of null: TypeError: Cannot read property 'range' of null
    at asTextEdit (/home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:100:46)
    at /home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:95:67
    at set (/home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:83:13)
    at asCompletionItem (/home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:95:9)
    at Array.map (native)
    at asCompletionResult (/home/wywrzal/git/vscode-php-intellisense/node_modules/vscode-languageclient/lib/protocolConverter.js:76:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

_Copied from original issue: Microsoft/vscode#11876_

**Comment by felixfbecker** [comment]
@dbaeumer This seems to be the same as #127 and broke completion support for PHP again :(

**Comment by felixfbecker** [comment]
If `textEdit` is not send, a different property that is `null` causes the same error:
```

{"result":{"isIncomplete":true,"items":[{"label":"<?php","kind":14,"detail":null,"documentation":null,"sortText":null,"filterText":null,"insertText":null,"range":null,"additionalTextEdits":null,"command":null,"data":null}]},"id":3,"jsonrpc":"2.0"}
shell.ts:437 Cannot read property 'title' of null: TypeError: Cannot read property 'title' of null
    at asCommand (/Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:222:35)
    at /Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:103:65
    at set (/Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:89:13)
    at asCompletionItem (/Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:103:9)
    at Array.map (native)
    at asCompletionResult (/Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:85:51)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by felixfbecker** [comment]
Looks like this is fixed on latest master, but not yet on VS Code Insiders?

https://sourcegraph.com/github.com/Microsoft/vscode-languageserver-node@f80a25f35487446aae86c469dc39a58e7e33b128/-/blob/client/src/protocolConverter.ts#L212:1-213:1

**Comment by dbaeumer** [comment]
@felixfbecker which verison of the node library are you using ?

**Comment by felixfbecker** [comment]
@dbaeumer sorry, you are right, VS Code has nothing to do with this. I am using version 3.0.3, which is the latest version and higher than `@next`.

**Comment by dbaeumer** [comment]
@felixfbecker is this still an issue then. The trace:
```
shell.ts:437 Cannot read property 'title' of null: TypeError: Cannot read property 'title' of null
    at asCommand (/Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:222:35)
    at /Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:103:65
    at set (/Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:89:13)
    at asCompletionItem (/Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:103:9)
    at Array.map (native)
    at asCompletionResult (/Users/felix/.vscode-insiders/extensions/felixfbecker.php-intellisense-0.0.12/node_modules/vscode-languageclient/lib/protocolConverter.js:85:51)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
Is on old code. The set function for example doesn't exist anymore in 3.0.3

**Comment by felixfbecker** [comment]
@dbaeumer I am sorry, I had a wrong symlink in my extension folder. I think this can be closed.

**Comment by dbaeumer** [comment]
@felixfbecker no problem. Happened to me as well :-)

Closing
